### ISSUE TITLE
好啊，很好啊（喜

### ISSUE THREAD

**Issue by cloudw233** [dzxgithub/BiliBiliAPITest#2]
非常好作品，英雄联盟，爱❤来自瓷器🇨🇳

**Comment by dzxgithub** [comment]
好的工作,英雄联盟,爱来自日本漆

**Comment by NicholasYang21** [comment]
> 非常好作品，英雄联盟，爱heart来自瓷器cn

说的道理，但是《敖厂长》是由“电棍”自主研发的一款全新锐刻系列电子烟模拟游戏。游戏发生在一个被称作「BiliBili」的幻想世界，在这里，被陈睿选中的人将被授予「樱桃炸弹」，导引小鬼之力‌​​​‌‌‌‌‌‌‌‌​​‌‌​‌‌‌​‌​。你将扮演一位名为「何同学」的神秘角色，在自由的旅行中邂逅性格各异、能力独特的键盘，和他们一起击败库克，找回失散的对未来的想象——同时，逐步发掘「Wallpaper Engine」的真相。
